funds:
  - code: "017652"
    name: "中航华证商飞高端制造产业指数发起C"
    enabled: 1
  - code: "014881"
    name: "天弘中证机器人ETF发起联接C"
    enabled: 1
  - code: "025833"
    name: "天弘中证电网设备主题指数发起C"
    enabled: 1
  - code: "021964"
    name: "天弘储能电池指数C"
    enabled: 1
  - code: "014564"
    name: "天弘沪深港创新药50ETF联接A"
    enabled: 1
  - code: "019260"
    name: "富国恒生红利ETF联接A"
    enabled: 1
  - code: "019059"
    name: "易方达中证绿色电力ETF联接发起式C"
    enabled: 1
  - code: "015968"
    name: "永赢半导体产业智选混合发起C"
    enabled: 1
  - code: "012863"
    name: "汇添富中证电池主题ETF发起式联接C"
    enabled: 1
  - code: "006787"
    name: "泰康港股通大消费指数C"
    enabled: 1
  - code: "008888"
    name: "华夏国证半导体芯片ETF联接C"
    enabled: 0
  - code: "011148"
    name: "南方军工改革灵活配置混合C"
    enabled: 0
  - code: "004433"
    name: "南方有色金属ETF联接C"
    enabled: 0
  - code: "024749"
    name: "博时中证卫星产业指数C"
    enabled: 0
  - code: "020900"
    name: "天弘中证全指通信设备指数发起C"
    enabled: 0
  - code: "012329"
    name: "天弘中证新能源指数增强C"
    enabled: 0
  - code: "001553"
    name: "天弘中证证券保险C"
    enabled: 0
  - code: "011967"
    name: "招商中证光伏产业指数C"
    enabled: 0
  - code: "018386"
    name: "招商中证全指软件ETF发起式联接C"
    enabled: 0
  - code: "013196"
    name: "招商中证新能源汽车指数C"
    enabled: 0
  - code: "016573"
    name: "招商中证银行AH价格优选ETF发起式联接C"
    enabled: 0
  - code: "012734"
    name: "易方达中证人工智能主题ETF联接C"
    enabled: 0
