[pytest]
filterwarnings = ignore::urllib3.exceptions.InsecureRequestWarning
env = uat
log_cli = true
log_cli_level = DEBUG
#引config.p中的环映变
; config_file = "config.py"
python_files = test_*.py
python_classes = Test*
python_functions = test_*
console_output_style = classic
markers = yaml_subdir(name): 指定该测试类或测试函数的数据子目录

[LOGGING]
log_file = /logs/log.log
max_bytes_each = 51200
backup_count = 10
fmt = |(asctime)s |(filename)s[line: |(lineno)d] |(levelname)s: |(message)s
logger_name = test_logger
log_level_in_console = 10
log_level_in_logfile = 10
console_log_on = 1
logfile_log_on = 1
